# Deployment

kind: Deployment
apiVersion: apps/v1
metadata:
  name: devweb  
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: devweb 
  template:
    metadata:
      name: devweb 
      labels: 
        app: devweb 
    spec: 
      containers: 
      - name: devweb 
        image: devweb:latest
        ports: 
        - containerPort: 8090

---

kind: Service 
apiVersion: v1 
metadata:
  name: devweb-svc
spec: 
  type: LoadBalancer
  selector:
    app: devweb 
  ports: 
  - targetPort: 8090
    port: 80
